# Source: jxboot-helmfile-resources/templates/local-secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jx-local-secrets
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: vault-infra
  data:
  - name: secrets.yaml
    key: secret/data/jx/local/secrets
    property: secrets.yaml
  template:
    type: Opaque
