# Source: jxboot-helmfile-resources/templates/repositories.yaml
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  name: "dev"
  labels:
    jenkins.io/gitSync: "false"
    gitops.jenkins-x.io/pipeline: 'environment'
  namespace: jx
spec:
  provider: "https://github.com"
  providerName: 'github'
  org: "jstrachan"
  repo: "env-configsync-bootv3-scratch3"
  description: "the git repository for the Dev environment"
  scheduler:
    kind: Scheduler
    name: "environment"
  httpCloneURL: https://github.com/jstrachan/env-configsync-bootv3-scratch3.git
