# Source: jx/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jx-jx
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jx-jx
subjects:
- kind: ServiceAccount
  name: jx
  namespace: jx
