# Source: wave/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: wave
    release: "pusher"
    chart: "wave-1.0.0"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'environment'
  name: pusher-wave
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - list
  - get
  - update
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  verbs:
  - list
  - get
  - update
  - patch
  - watch
