# Source: wave/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: wave
    release: "pusher"
    chart: "wave-1.0.0"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'environment'
  name: pusher-wave
  namespace: jx
