apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins
  namespace: jx
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - jstrachan/env-configsync-bootv3-scratch2
      require_self_approval: true
    blunderbuss: {}
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      maps:
        env/prow/config.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    heart: {}
    owners: {}
    plugins:
      jstrachan/env-configsync-bootv3-scratch2:
      - config-updater
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    slack: {}
    triggers:
    - repos:
      - jstrachan/env-configsync-bootv3-scratch2
      trusted_org: jstrachan
